name:                neural
version:             0.1.0.0
github:              "arjaz/neural"
author:              "Eugene Rossokha"
maintainer:          "arjaz@protonmail.com"

dependencies:
- base >= 4.7 && < 5
- matrix
- vector

library:
  source-dirs: src

executables:
  neural-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neural
